### ISSUE TITLE
make NXWEB_MAX_NET_THREADS a configurable parameter

### ISSUE THREAD

**Issue by byzhang** [byzhang/nxweb#1]

**Comment by lyxm** [comment]
Means configurable with a command line flag?

**Comment by byzhang** [comment]
Yes
2015年10月17日 20:32，"lyxm" notifications@github.com写道：

**Comment by byzhang** [comment]
Maybe like the way how port is set.
2015年10月17日 20:33，"BY" byzhang@gmail.com写道：

**Comment by lyxm** [comment]
code change finished.  how can I run and test?  and need to figure out how to use git :-(

**Comment by byzhang** [comment]
It's the main purpose of this issue :-) But help.github.com is a great
resource.
Basically you need fork the repo, clone to the local, make code changes,
push to your repo, and then create a pull request.
c.f. https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/pushing-to-a-remote/
https://help.github.com/articles/creating-a-pull-request/

Re: testing, you can run the sample following
https://github.com/byzhang/nxweb/blob/master/INSTALL#L79. And you can use
htop to check the number of threads.

Thanks,
-B

**Comment by lyxm** [comment]
Need to set up ssh agent etc
